name: PR Test and Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 사용 중인 Node.js 버전으로 수정하세요.

      - name: Install server dependencies
        run: |
          cd server # 서버 디렉토리로 이동
          npm install

      - name: Install client dependencies
        run: |
          cd client # 클라이언트 디렉토리로 이동
          npm install

      - name: Run server tests
        run: |
          cd server # 서버 디렉토리로 이동
          npm test

      - name: Run client tests
        run: |
          cd client # 클라이언트 디렉토리로 이동
          npm test

      - name: Lint and build server
        run: |
          cd server # 서버 디렉토리로 이동
          npm run lint
          npm run build

      - name: Lint and build client
        run: |
          cd client # 클라이언트 디렉토리로 이동
          npm run lint
          npm run build
